/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface CustomComponent {
    }
}
declare global {
    interface HTMLCustomComponentElement extends Components.CustomComponent, HTMLStencilElement {
    }
    var HTMLCustomComponentElement: {
        prototype: HTMLCustomComponentElement;
        new (): HTMLCustomComponentElement;
    };
    interface HTMLElementTagNameMap {
        "custom-component": HTMLCustomComponentElement;
    }
}
declare namespace LocalJSX {
    interface CustomComponent {
    }
    interface IntrinsicElements {
        "custom-component": CustomComponent;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "custom-component": LocalJSX.CustomComponent & JSXBase.HTMLAttributes<HTMLCustomComponentElement>;
        }
    }
}
